./configure \
--sbin-path=/usr/local/sbin \
--with-md5=/usr/lib \
--with-openssl=/usr/lib/ssl \
--conf-path=/usr/local/etc/nginx/nginx.conf \
--error-log-path=/var/local/log/nginx-error.log \
--http-log-path=/var/local/log/nginx-access.log \
--http-client-body-temp-path=/var/tmp/nginx/client_body_temp \
--http-proxy-temp-path=/var/tmp/nginx/proxy_temp \
--http-fastcgi-temp-path=/var/tmp/nginx/fastcgi_temp \
--pid-path=/var/run/nginx.pid
