#!/bin/sh

#TODO:
# [ ] install with symlinks instead of copy
# [ ] backup of existing files
# [ ] implement 'uninstall'

cp -Rf .vim ~/
cp -Rf .tools ~/

rm -Rf ~/.zshkit
cp -Rf zshkit ~/.zshkit
~/.zshkit/install

cp -f .gitconfig ~/
cp -f .vimrc ~/
cp -f .screenrc ~/
cp -f .gitignore ~/
cp -f .cshrc ~/

