#!/bin/sh

CUR=`pwd`

echo "~/.tools"
cp -Rf tools ~/.tools
ls -al ~/.tools


echo "~/.screenrc"
cp -f screenrc ~/.screenrc

if [ ! -e ~/.gitconfig.backup ]; then
  echo "backup .gitconfig .."
  mv -f ~/.gitconfig ~/.gitconfig.backup
fi

echo "~/.gitconfig"
cp -f gitconfig ~/.gitconfig

echo "Enter your name for git user.name:\c"
read GIT_USER_NAME

echo "Enter your email for git user.email:\c"
read GIT_USER_EMAIL

git config --global --replace-all user.name $GIT_USER_NAME
git config --global --replace-all user.email $GIT_USER_EMAIL
git config --global --replace-all core.excludesfile ~/.gitconfig

echo "~/.gitignore"
cp -f gitignore ~/.gitignore


echo "Installing zshkit"

rm -Rf ~/.zshkit
cp -Rf zshkit ~/.zshkit
~/.zshkit/install

echo "Adding homedir extra lines to ~/.zshrc"
cat zshrc_addons >> ~/.zshrc

echo "Done"

echo "Starging janus automated installer"

curl -Lo- https://bit.ly/janus-bootstrap | bash

echo "Installing non janus vim plugins"
cp -r janus ~/.janus

echo "Customizing janus"
cp vimrc.before ~/.vimrc.before
cp vimrc.after ~/.vimrc.after
