#!/bin/sh

echo "~/.tools"
cp -Rf tools ~/.tools
ls -al ~/.tools


echo "~/.screenrc"
cp -f screenrc ~/.screenrc

echo "~/.gitconfig"
cp -f gitconfig ~/.gitconfig

echo "~/.gitignore"
cp -f gitignore ~/.gitignore


echo "Installing zshkit"

rm -Rf ~/.zshkit
cp -Rf zshkit ~/.zshkit
~/.zshkit/install

echo "Adding homedir extra lines to ~/.zshrc"
cat zshrc_addons >> ~/.zshrc

echo "Done"
echo "To do local customization create ~/.zshrc.local and add strings into it\n"

echo "Removing existing vim dotfiles"
if [ ! -e ~/.vim.backup ]; then
  echo "backup .vim .."
  mv -f ~/.vim ~/.vim.backup
fi
if [ ! -e ~/.vimrc.backup ]; then
  echo "backup .vimrc .."
  mv -f ~/.vimrc ~/.vimrc.backup
fi

rm -Rf ~/.vim
rm -f ~/.vimrc

echo ".vimrc"
cp -f vimrc ~/.vimrc
