#!/usr/bin/env ruby
needle = ARGV.shift
if needle.nil? then
  puts "Use: rg pattern [path] [grep options]"
  exit
end
path = ARGV.shift || './'
if path =~ /^-/
    ARGV.unshift path
    path = './'
end

extensions = %w(php pm pl xml js conf rb html erl sh)
name_conditions = extensions.map{|ext| "-iname \*.#{ext}"}.join(' -o ')

cmd = "find #{path} -type f \\( #{name_conditions} \\) -exec grep -nE '#{needle}' --color=always #{ARGV.join ' '} {} + | sed -e 's/:/ \+/'"
puts cmd
puts `#{cmd}`
