#!/usr/bin/env ruby
needle = ARGV.shift
if needle.nil? then
  puts "Use: rg pattern [path] [grep options]"
  exit
end
path = ARGV.shift || './'
if path =~ /^-/
    ARGV.unshift path
    path = './'
end
#puts `grep -RE #{needle} #{path} | grep -vE "log|svn" | grep #{needle} --colour=always`
puts `find #{path} -type f -regex '.*(\.php|\.pm|\.pl|\.xml|\.js|\.conf|\.rb)' -exec grep -nE '#{needle}' --color=always #{ARGV.join ' '} {} + \; | sed -e 's/:/ \+/'`

#puts `find -E #{path} -type f -regex '.*(\.php|\.pm|\.pl|\.xml|\.js|\.conf)' -exec grep -nE "#{needle}" --color=always #{ARGV.join ' '} {} + | sed -e 's/:/ \+/'`
