#!/usr/bin/env ruby
needle = ARGV.shift
if needle.nil? then
  puts "Use: rg pattern [path] [grep options]"
  exit
end
path = ARGV.shift || './'
if path =~ /^-/
    ARGV.unshift path
    path = './'
end

extensions = %w(php pm pl xml js conf rb html erl sh)
regex = extensions.map{|i| "\\.#{i}"}.join('|')
regex = ".*(#{regex})"

cmd = "find #{path} -type f -regex '#{regex}' -exec grep -nE '#{needle}' --color=always #{ARGV.join ' '} {} \\; | sed -e 's/:/ \+/'"
puts cmd
puts `#{cmd}`

